// <auto-generated />
using System;
using Graduation_project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Graduation_project.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241021170210_Initial_Subjects")]
    partial class Initial_Subjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Graduation_project.Models.Attendance", b =>
                {
                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<int>("all_lessons")
                        .HasColumnType("int");

                    b.Property<int>("attendent_lessons")
                        .HasColumnType("int");

                    b.Property<string>("full_name_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("missed_lessons")
                        .HasColumnType("int");

                    b.HasKey("ID_student");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Graduation_project.Models.Class_list", b =>
                {
                    b.Property<int>("ID_class")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_class"));

                    b.Property<int>("ID_teacher")
                        .HasColumnType("int");

                    b.Property<int>("biology_teacher")
                        .HasColumnType("int");

                    b.Property<int>("math_teacher")
                        .HasColumnType("int");

                    b.Property<string>("name_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("world_history_teacher")
                        .HasColumnType("int");

                    b.HasKey("ID_class");

                    b.HasIndex("ID_teacher");

                    b.ToTable("Class_list");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_PE", b =>
                {
                    b.Property<int>("ID_PE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PE"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PE");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_PE");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_biology", b =>
                {
                    b.Property<int>("ID_biology")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_biology"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_biology");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_biology");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_computer_project", b =>
                {
                    b.Property<int>("ID_computer_project")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_computer_project"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_computer_project");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_computer_project");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_english", b =>
                {
                    b.Property<int>("ID_english")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_english"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_english");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_english");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_geography", b =>
                {
                    b.Property<int>("ID_geography")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_geography"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_geography");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_geography");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_informathicsIT", b =>
                {
                    b.Property<int>("ID_informathicsIT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_informathicsIT"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_informathicsIT");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_informathicsIT");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_math", b =>
                {
                    b.Property<int>("ID_math")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_math"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_math");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_maths");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_physics", b =>
                {
                    b.Property<int>("ID_physics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_physics"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_physics");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_physics");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_programming", b =>
                {
                    b.Property<int>("ID_programming")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_programming"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_programming");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_programming");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_ukr_history", b =>
                {
                    b.Property<int>("ID_ukr_history")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ukr_history"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_ukr_history");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_history");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_ukr_lang", b =>
                {
                    b.Property<int>("ID_ukr_lang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ukr_lang"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_ukr_lang");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_ukr_lang");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_ukr_lit", b =>
                {
                    b.Property<int>("ID_ukr_lit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ukr_lit"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_ukr_lit");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_ukr_lit");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_world_history", b =>
                {
                    b.Property<int>("ID_world_history")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_world_history"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_world_history");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_world_history");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_world_lit", b =>
                {
                    b.Property<int>("ID_world_lit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_world_lit"));

                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_world_lit");

                    b.HasIndex("ID_student");

                    b.ToTable("Current_Grades_world_lit");
                });

            modelBuilder.Entity("Graduation_project.Models.Students", b =>
                {
                    b.Property<int>("ID_student")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_student"));

                    b.Property<int>("Average_grage")
                        .HasColumnType("int");

                    b.Property<int>("Count_grades")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_student")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position_in_class")
                        .HasColumnType("int");

                    b.Property<int>("Position_in_paralel")
                        .HasColumnType("int");

                    b.Property<string>("Surname_student")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_student");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Graduation_project.Models.Teachers", b =>
                {
                    b.Property<int>("ID_teacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_teacher"));

                    b.Property<string>("MiddleName_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("form_master_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_admin")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_form_master")
                        .HasColumnType("bit");

                    b.Property<string>("password_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_teacher");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Graduation_project.Models.schedule_days", b =>
                {
                    b.Property<int>("ID_schedule_day")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_schedule_day"));

                    b.Property<int>("class_id")
                        .HasColumnType("int");

                    b.Property<string>("day_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fifth_lesson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_lesson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fourth_lesson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("second_lesson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("third_lesson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_schedule_day");

                    b.HasIndex("class_id");

                    b.ToTable("schedule_day");
                });

            modelBuilder.Entity("Graduation_project.Models.Attendance", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithOne("Attendance")
                        .HasForeignKey("Graduation_project.Models.Attendance", "ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Class_list", b =>
                {
                    b.HasOne("Graduation_project.Models.Teachers", "Teacher")
                        .WithMany()
                        .HasForeignKey("ID_teacher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_PE", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_biology", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_computer_project", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_english", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_geography", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_informathicsIT", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_math", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_physics", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_programming", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_ukr_history", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_ukr_lang", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_ukr_lit", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_world_history", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Current_grades_world_lit", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithMany()
                        .HasForeignKey("ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.schedule_days", b =>
                {
                    b.HasOne("Graduation_project.Models.Class_list", "Class")
                        .WithMany()
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Graduation_project.Models.Students", b =>
                {
                    b.Navigation("Attendance");
                });
#pragma warning restore 612, 618
        }
    }
}
