// <auto-generated />
using System;
using Graduation_project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Graduation_project.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240916050034_RowsToTeachers")]
    partial class RowsToTeachers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Graduation_project.Models.Attendance", b =>
                {
                    b.Property<int>("ID_student")
                        .HasColumnType("int");

                    b.Property<int>("all_lessons")
                        .HasColumnType("int");

                    b.Property<int>("attendent_lessons")
                        .HasColumnType("int");

                    b.Property<string>("full_name_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("missed_lessons")
                        .HasColumnType("int");

                    b.HasKey("ID_student");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Graduation_project.Models.Students", b =>
                {
                    b.Property<int>("ID_student")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_student"));

                    b.Property<int>("Average_grage")
                        .HasColumnType("int");

                    b.Property<int>("Count_grades")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_student")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position_in_class")
                        .HasColumnType("int");

                    b.Property<int>("Position_in_paralel")
                        .HasColumnType("int");

                    b.Property<string>("Surname_student")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_student");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Graduation_project.Models.Teachers", b =>
                {
                    b.Property<int>("ID_teacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_teacher"));

                    b.Property<string>("MiddleName_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("form_master_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_form_master")
                        .HasColumnType("bit");

                    b.Property<string>("password_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_teacher");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Graduation_project.Models.Attendance", b =>
                {
                    b.HasOne("Graduation_project.Models.Students", "Student")
                        .WithOne("Attendance")
                        .HasForeignKey("Graduation_project.Models.Attendance", "ID_student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Graduation_project.Models.Students", b =>
                {
                    b.Navigation("Attendance");
                });
#pragma warning restore 612, 618
        }
    }
}
